# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: medcom
canonical: http://example.org/fhir/fish
version: 0.1.0
name: FFB-reporting Testscripts
title: FFB-reporting Testscripts
status: draft
publisher: Anders Jensen
contact:
  - name: MedCom
    telecom:
      - system: email
        value: fhir@medcom.dk
description: Testscripts for FFB-reporting
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Artifacts Summary: artifacts.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
